### ISSUE TITLE
Crash when SteamVR menu opens in Linux

### ISSUE THREAD

**Issue by CrispyPin** [icosa-gallery/open-brush#138] opened 2021-06-23 16:48 UTC
When I open the steamVR dashboard while in Openbrush, the HMD and Openbrush freezes entirely until I force quit Openbrush. When i have killed Openbrush, Steamvr won't close properly and there is a background process left over from openbrush that i have to manually kill too.

Sytem info:
Openbrush version: **0.3.0**, **0.3.12** and **0.3.24**
SteamVR: **v1.14.16**
HMD: Valve Index
OS: Pop!_os 20.10
GPU: Radeon RX 6800XT
CPU: Ryzen 5 5600X

**Comment by Cloudperry** [comment] 2022-01-19 00:58
I can confirm this is still happening on Openbrush 0.4.22. If I start using Openbrush more, I will maybe look into getting some useful logs or information on this.

Setup and software:
SteamVR version: Beta 1.21.6
GPU driver version: Mesa 21.3.4
OS: Arch Linux
HMD: Valve Index
GPU: RX Vega 56
CPU: Ryzen 3600

**Comment by Cloudperry** [comment] 2022-01-28 00:25
Yep. Still happens on 1.0.0. Didn't try this before, but now I can at least recover from the freeze by manually ending the Openbrush process. After ending it I can play games just fine and Steamvr works. 

Maybe the Linux release of Openbrush should be labeled as a Beta because of this bug? I think it definitely should be, if this affects all Linux users. The menu is quite important for switching games etc. With this bug Openbrush is impossible to quit inside vr without making an easy kb shortcut for killing it or something.

**Comment by oxr463** [comment] 2022-03-08 23:31
Does this occur with the Windows release running in Proton?

**Comment by CrispyPin** [comment] 2022-03-12 16:28
It does not happen under proton

**Comment by merulaxr** [comment] 2022-10-01 21:26
As we've moved away from SteamVR to OpenXR we won't be fixing this issue. We're pushing Unity hard to support building OpenXR natively to Linux. Sorry for the inconvenience. I'd love to know if our OpenXR build functions through Proton if anyone is able to test.

**Closed by merulaxr** 2022-10-01 21:27 UTC
Labels: bug, wontfix
