### ISSUE TITLE
Eraser and Selection tools not functioning (Quest 1, Standalone, AppLab))

### ISSUE THREAD

**Issue by Reid1999** [icosa-gallery/open-brush#398] opened 2023-02-14 03:37 UTC
Hi! Just recently downloaded the update, and noticed the eraser tool was no longer functioning. Undo is still working to remove brushstrokes, but eraser turns red and doesn't remove any when it passes through. I've tried experimental mode, re-installing and turning my quest on and off. 

Otherwise, my Fianceé and I adore your app! I use it as an education tool in my classroom, and she loves to draw on my personal quest at home! Thank you for this amazing app!

**Comment by mikeskydev** [comment] 2023-02-14 09:33
Hi, we had this bug report come through our Discord but hadn't added it here, thanks! To add some more info, this works fine on the Quest 2. We think the Quest 1 has some issues related to the change to Vulkan that was required for our specific app circumstances.

**Comment by mikeskydev** [comment] 2023-07-11 15:53
The root cause has been found:

The Vulkan driver for Quest 1 does not support geometry shaders, which breaks the implementation for selection.
http://vulkan.gpuinfo.org/displayreport.php?id=12292#features

OpenGL previously required implementations to support geometry shaders, but Vulkan 1.0 has no such requirement.

**Comment by mikeskydev** [comment] 2023-08-11 16:26
Fixed in #475! Thanks to everyone who reported.

**Closed by mikeskydev** 2023-08-11 16:26 UTC
Labels: bug
