### ISSUE TITLE
Old version of the Oculus Integration package

### ISSUE THREAD

**Issue by fabio914** [icosa-gallery/open-brush#25] opened 2021-02-01 00:25 UTC
Open brush uses version 1.41.0 and the current version is 23.1.

Updating the Oculus Integration package can help solve some issues with the Mixed Reality capture on the Oculus Quest 1 and 2 ([example](https://twitter.com/fabio914/status/1332724521497931777)). The new version can also open some possibilities, such as hand tracking, higher frame rates, and etc.

**Comment by mikeage** [comment] 2021-02-02 09:46
I just tried upgrading from 1.41.0 to 23.1, following the instructions at https://developer.oculus.com/documentation/unity/unity-import/?device=QUEST (though I skipped the deletion of a bunch of files that started with Oculus, although I did, obviously, delete Assets/Oculus) and it seems to work (it does create two new files that need to be added to .gitignore;  Assets/Resources/OVRPlatformToolSettings.asset and Assets/Resources/OVRPlatformToolSettings.asset.meta). In a five minute test, everything seemed ok (note that I'm using Android SDK 29 rather than the 26 that's in master; I also have PR 18 merged locally).

I don't know enough to try doing anything new with this, but as a base, it looks like it's safe enough to try using the newer version.

**Comment by billyquith** [comment] 2021-02-02 12:15
That's what I've been using too. I couldn't get 1.41 to work (missing `HandState`?).

**Comment by mikeage** [comment] 2021-02-02 17:31
Ok, so maybe we should just update the README to say to use 23.1 (and update .gitignore). I've opened a PR, and maybe a few other people can test and confirm.

**Comment by fabio914** [comment] 2021-02-02 17:56
I wonder if there's a way we can automate downloading this dependency from Oculus. Perhaps a simple script to download it and include it with the project (part of a "setup" script maybe?), then we could ensure that everyone is on the same version while developing/building and that this script will have be updated when we start using a new version.

**Comment by fabio914** [comment] 2021-02-02 17:58
@billyquith I believe hand tracking wasn't part of that version, so potentially the project is already using objects from a newer version. It's important that we find a way to ensure that people are using the same versions of these dependencies.

**Comment by mikeage** [comment] 2021-02-02 18:00
Automating the download (easy) and installation (umm....) would also be very helpful for doing CI at some point, but while I'm happy to write python code to help, I don't know enough Unity to do it. I'm not even clear if adding the package does anything besides adding Assets/Oculus files; maybe they can be tracked in source control?

**Comment by fabio914** [comment] 2021-02-02 20:12
Yeah, having this in source control is another option.

**Comment by TimAidley** [comment] 2021-02-03 02:22
The issue is that the Oculus license does not allow redistribution of all of the files in the integration.

**Comment by mikeage** [comment] 2021-02-03 04:36
Ah, ok, that’s a blocker!

By any chance, do you know how to script the installation of a unity package?

**Comment by TimAidley** [comment] 2021-02-03 04:40
The issue is we can't just http fetch it as you have to agree to T&C before downloading it. However, we could make a wizard that would detect if it is installed, and guide you through the process.

**Comment by mikeage** [comment] 2021-02-03 04:52
Right, missed that. I'm not doing well here ;-)

**Closed** 2021-02-03 20:39 UTC
