### ISSUE TITLE
[Android] Camera tool breaks after 1 or 2 uses

### ISSUE THREAD

**Issue by andybak** [icosa-gallery/open-brush#61] opened 2021-03-18 17:43 UTC
Reported by @daveaudio224on Discord:

> Running Open Brush on both App lab and sidequest on Quest 2 - there’s a glitch with the camera where it might take 1-2 pictures, but the camera viewfinder then turns to a horizontal white stripe.

https://discord.com/channels/783806589991780412/804677406572150814/822108368587849808

**Comment by andybak** [comment] 2021-03-18 17:45
Discord user: @Noartnoglory :

> Does it look like this? I had posted above in Feb. But wasn't sure if it was an ongoing bug.

![image](https://user-images.githubusercontent.com/60035/111672190-9fb20e00-8811-11eb-9855-6cfc5ff92b3e.png)

Discord user @daveaudio224:

> The photos that are taken usually have a block like this in the lower left yes (but sometimes multi colored). But it’s the viewfinder itself that looks like this — 50% white and 50% black — and you can’t see out of the viewfinder to really aim the camera. However you can still take a gif and see from the viewfinder when snapping a gif.

**Comment by mikeskydev** [comment] 2021-04-09 22:23
It appears the snapshot feature breaks when switching to a different capture method (gif) then back to snapshot. This only happens on Quest. The bug is also reproducible in the last official Tilt Brush release.

**Comment by Nicorr** [comment] 2022-03-07 12:06
This bug is still ongoing on Quest.

Platform: Meta Quest 2
App Versions: All

When taking Snaphots, the documentation recommends a maximum "SnapshotWidth" and Height of 4096. This works well, except if you close the Snapshot tool and reopen it. If you do, black and white line are displayed on the preview, and the snapshots have those lines in the corner of the picture taken.

It looks like opening the snapshot tool instantiates something in the memory twice, which shows on Quest mainly due to the hardware specs being more restraint, but is probably also the case on the other platforms.

**Comment by merulaxr** [comment] 2022-04-11 08:16
Possible fix via wildc4rd#9436 on Discord: https://discord.com/channels/783806589991780412/806934697237938216/962793147363098748

> I found a bug in Openbrush when the auto gif is created. The gifs get white glitches. I checked this on 1.0.0 now only, but I think it's been like this in tiltbrush already. So I analized with a anigif tool why there is this white flickering that occurs sometimes and found what fixes it.
In the first frame of the anigif transparency needs to be disabled. Then it works. 
Maybe someone could fix this at some point for anigif creation in Openbrush😊

**Comment by merulaxr** [comment] 2022-11-18 21:57
This appears to have been fixed with #276!

**Closed by merulaxr** 2022-11-18 21:57 UTC
Labels: bug
